name: Android Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Create google-services.json
      env:
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: |
        if [ -n "$GOOGLE_SERVICES_JSON" ]; then
          echo "$GOOGLE_SERVICES_JSON" > android/app/google-services.json
        else
          echo "Error: GOOGLE_SERVICES_JSON secret is not set"
          exit 1
        fi

    - name: Sync Capacitor
      run: npx cap sync || (echo "npx cap sync failed"; exit 1)

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Create debug keystore
      run: |
        mkdir -p ~/.android
        keytool -genkeypair -alias androiddebugkey -keypass android -keystore ~/.android/debug.keystore -storepass android -dname "CN=Android Debug,O=Android,C=US" -keyalg RSA -keysize 2048 -validity 10000 || echo "Failed to create debug.keystore"

    - name: Check debug keystore location
      run: |
        echo "Listing files in /home/runner/.android/"
        ls -la /home/runner/.android/ || echo "Directory /home/runner/.android/ not found"
        echo "Listing files in /home/runner/.config/.android/"
        ls -la /home/runner/.config/.android/ || echo "Directory /home/runner/.config/.android/ not found"

    - name: Make gradlew executable
      run: chmod +x android/gradlew

    - name: Build with Gradle
      working-directory: android
      run: ./gradlew assembleDebug || (echo "gradlew assembleDebug failed"; exit 1)

    - name: List build outputs
      working-directory: android
      run: find app/build/outputs -type f

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: android/app/build/outputs/apk/debug/app-debug.apk
